name: save_it
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  timeago: ^3.6.0
  flutter_localized_locales: ^2.0.5
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.8
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.2
  rxdart: ^0.27.7
  drift: ^2.13.2
  sqlite3_flutter_libs: ^0.5.18
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  ffi: ^2.1.0
  path_provider: ^2.1.1
  mobile_scanner: ^3.5.5
  protocol_handler: ^0.1.5
  flutter_native_splash: ^2.3.6
  share_plus: ^7.2.1
  window_manager: ^0.3.7
  tray_manager: ^0.2.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.1
  vclibs: ^0.1.0
  launch_at_startup: ^0.2.2
  sentry_flutter: ^7.13.2
  sentry_dart_plugin: ^1.6.3
  combine: ^0.5.6
  path: ^1.8.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  meta: ^1.10.0
  dartx: ^1.2.0
  uuid: ^4.2.1
  tint: ^2.0.1
  accessibility_tools: ^1.0.0
  neat_periodic_task: ^2.0.1
  retry: ^3.1.2
  watcher: ^1.1.0
  go_router: ^12.1.1
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  percent_indicator: ^4.2.3
  sliver_tools: ^0.2.12
  flutter_adaptive_scaffold: ^0.1.7+1
  humanizer: ^2.2.0
  upgrader: ^8.3.0
  toastification: ^1.1.0
  version: ^3.0.2
  posix: ^6.0.1
  win32: ^5.1.1
  qr_flutter: ^4.1.0
  native_dio_adapter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  riverpod_generator: ^2.3.8
  drift_dev: ^2.13.2
  ffigen: ^8.0.2
  slang_build_runner: ^3.25.0
  flutter_gen_runner: ^5.3.2
  go_router_builder: ^2.3.4
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.6
  icons_launcher: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/core/geoip.db
    - assets/core/geosite.db
    - assets/images/logo.svg
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/images/tray_icon_connected.ico
    - assets/images/tray_icon_disconnected.ico

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

icons_launcher:
  image_path: "assets/images/source/ic_launcher_border.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/source/ic_launcher_border.png"
      # adaptive_background_color: "#ffffff"
      adaptive_background_image: "assets/images/source/ic_launcher_background.png"
      adaptive_foreground_image: "assets/images/source/ic_launcher_foreground.png"
      adaptive_round_image: "assets/images/source/ic_launcher_round.png"
      adaptive_monochrome_image: "assets/images/source/ic_launcher_monochrome.png"
    ios:
      enable: true
      image_path: "assets/images/source/ic_launcher_rectangle.png"
    macos:
      enable: true
      image_path: "assets/images/source/ic_launcher_border.png"
    linux:
      enable: true
      image_path: "assets/images/source/ic_launcher_border.png"
    windows:
      enable: true
      image_path: "assets/images/source/ic_launcher_transparent.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/images/source/ic_launcher_foreground.png

ffigen:
  name: "SingboxNativeLibrary"
  description: "Bindings to Singbox"
  output: "lib/gen/singbox_generated_bindings.dart"
  headers:
    entry-points:
      - "libcore/bin/libcore.h"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  log_level: info
  ignore_missing: true
